01 Python Basics

In [1]:
print("Hello, Python!")

Hello, Python!


In [2]:
num = 32
name = "Tushar"
print(num, name)
type(num), type(name)

32 Tushar


(int, str)

In [3]:
print(type(num))
print(type(name))

<class 'int'>
<class 'str'>


In [4]:
num

32

In [5]:
# Addition of two numbers
num1 = 47
num2 = 53
add = num1 + num2
print("Addition is: ", add)

Addition is:  100


In [6]:
# Addition of two numbers
num1 = 47
num2 = 53
add = num1 + num2
print("Addition is: %d" % add)

Addition is: 100


In [7]:
num = 56.74
type(num)

float

In [8]:
# Addition of two strings
name1 = input('Enter first name: ')
name2 = input('Enter second name: ')
add = name1 + " " + name2
print("Addition is: ", add)

Addition is:  Dipankar Majumder


In [9]:
# Addition of two numbers with custom input
name1 = int(input('Enter first name: '))
name2 = int(input('Enter second name: '))
add = name1 + name2
print("Addition is: ", add)

Addition is:  32


In [10]:
num = 10
if num >= 0:
    print('+ve number')
else:
    print('-ve number')

+ve number


Match Case

In [11]:
num = 10
match num:
    case num if num > 0:
        print('+ve number')
    case num if num < 0:
        print('-ve number')
    case _:
        print('Zero')

+ve number


##### Loop

In [12]:
count = 0
while count < 10:
    print('Tushar')
    count += 1

Tushar
Tushar
Tushar
Tushar
Tushar
Tushar
Tushar
Tushar
Tushar
Tushar


In [13]:
count = 0
while (count := count + 1) < 10:
    print(f'Tushar{count}')

Tushar1
Tushar2
Tushar3
Tushar4
Tushar5
Tushar6
Tushar7
Tushar8
Tushar9


In [14]:
for num in 45, 22, 14, 35, 26, 41,25:
    print(num ** 2)

2025
484
196
1225
676
1681
625


Lambda Function

In [15]:
print(list(
    map(
        lambda x: x ** 2, 
        [45, 22, 14, 35, 26, 41,25]
        )))

[2025, 484, 196, 1225, 676, 1681, 625]


##### Function

In [16]:
def square(num):
    return num ** 2
print(square(23))

529


In [17]:
def squareCube(num):
    val1 = num ** 2
    val2 = num ** 3
    return val1, val2
print(squareCube(3))

(9, 27)


##### List

In [18]:
x = [1, 2, 3, 4]
type(x)

list

In [19]:
x[3]

4

In [20]:
x[3] = 8
x

[1, 2, 3, 8]

Reverse List

In [21]:
x[::-1]

[8, 3, 2, 1]

##### Tuple

In [22]:
y = (1, 2, 3, 4)
type(y)
y[3]

4

In [23]:
y[3] = 8

TypeError: 'tuple' object does not support item assignment

In [24]:
z = 34, 12, 54, 36, 78, 98
print(z)
type(z)

(34, 12, 54, 36, 78, 98)


tuple

##### Dictionary

In [25]:
d = {
    2: 45,
    3: 67,
    5: 18,
    10: 34
}
print(d)
print(d[3])
type(d)

{2: 45, 3: 67, 5: 18, 10: 34}
67


dict

Get key from value

In [26]:
print(list(d.keys())[list(d.values()).index(45)])

2


##### Set

In [27]:
s = {5, 6, 4, 5, 6, 7, 9, 7, 6, 5, 4, 5, 6, 8}
s.add(99)
s

{4, 5, 6, 7, 8, 9, 99}

##### Math Library

In [28]:
import math
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.

        The result is between 0 and pi.

    acosh(x, /)
        Return the inverse hyperbolic cosine of x.

    asin(x, /)
        Return the arc sine (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    asinh(x, /)
        Return the inverse hyperbolic sine of x.

    atan(x, /)
        Return the arc tangent (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.

        Unlike atan(y/x), the signs of both x and y are considered.

    atanh(x, /)
        Return the inverse hyperbolic tangent of x.

    cbrt(x, /)
        Return the cube root of x.

    ceil(x, /)
        Return the ceiling of x as an Integral.

        This i

In [29]:
math.sqrt(23)

4.795831523312719

In [30]:
math.sin(12)

-0.5365729180004349

In [31]:
math.factorial(12)

479001600

In [32]:
math.pi

3.141592653589793

In [33]:
math.e

2.718281828459045

In [34]:
import time
time.asctime()

'Tue Jan  7 09:45:59 2025'

In [35]:
print('Hello')
time.sleep(5)
print('World')

Hello
World


##### Object Oriented Programming

In [36]:
class Person:
    def __init__(self, name: str, age: int) -> None:
        self.name = name
        self.age = age
    def __str__(self) -> str:
        return f"Name: {self.name}, Age: {self.age}"
    def __repr__(self) -> str:
        return f"Name: {self.name}, Age: {self.age}"
    def show(self) -> None:
        print('Values are: ', self.name, self.age)
    def is_elegible(self) -> None:
        if self.age < 18:
            print('NOT eligible for driving')
        else:
            print('Eligible for Driving')

person = Person("Dipankar Majumder", 24)
person = Person(name="Dipankar Majumder", age=24)
print(person)
person.is_elegible()

Name: Dipankar Majumder, Age: 24
Eligible for Driving


##### Array Operations (NumPy)

In [37]:
import numpy as np

In [38]:
x = np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
num = np.array([56, 33, 12, 54, 37, 94, 62])

In [40]:
num

array([56, 33, 12, 54, 37, 94, 62])

In [41]:
num.dtype

dtype('int32')

In [42]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [43]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
matrix.size

6

In [45]:
matrix[:, -1]

array([3, 6])

In [46]:
np.zeros([10, 10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [47]:
np.random.rand(10, 10)

array([[0.84750242, 0.25912192, 0.19496157, 0.04170238, 0.65217435,
        0.32400742, 0.0471598 , 0.05232951, 0.28746939, 0.43747115],
       [0.42779508, 0.44940505, 0.91660559, 0.99105319, 0.94746148,
        0.78604573, 0.85984593, 0.4880985 , 0.4186593 , 0.20472066],
       [0.29588845, 0.236901  , 0.53835111, 0.45687866, 0.88613413,
        0.43807764, 0.41968148, 0.19248488, 0.55662716, 0.37862943],
       [0.78447407, 0.61227041, 0.60886108, 0.79039753, 0.38495533,
        0.77097096, 0.80792455, 0.98574418, 0.57954897, 0.04220653],
       [0.47909791, 0.29734223, 0.1604929 , 0.0346922 , 0.96318912,
        0.63550777, 0.47899653, 0.92297888, 0.01618043, 0.73586663],
       [0.28487693, 0.97056812, 0.37577201, 0.92748689, 0.66453274,
        0.87767527, 0.1470524 , 0.6640203 , 0.29918901, 0.24279689],
       [0.62066813, 0.1241974 , 0.31485729, 0.91194098, 0.70235836,
        0.03662281, 0.17276524, 0.68438322, 0.11737758, 0.23908268],
       [0.57369613, 0.86064515, 0.7591522