##### Affine Transformation

In [1]:
import numpy as np
import cv2

In [2]:
img = cv2.imread('images/sachin.jpg')

In [7]:
tx = 50 # translation-x
ty = 100 # translation-y
angle = 45 # rotation
scale = 0.8 # scaling factor
shear_x = 0.25 # tilt on x axis
shear_y = 0.3 # tilt on y axis

# define the affine transformation matrix
M = np.float32([[scale * np.cos(np.radians(angle)), shear_x,                            tx],
                [shear_y,                           scale * np.sin(np.radians(angle)),  ty]])

In [8]:
img_affine = cv2.warpAffine(img, M, (img.shape[1], img.shape[0]))

In [10]:
cv2.imshow('Final Image', img_affine)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
M1 = np.array([[4, 5, 6],
               [1, 2, 3]])
M2 = np.array([[2, 8, 9],
               [0, 5, 7]])
print(M1)
print(M2)

[[4 5 6]
 [1 2 3]]
[[2 8 9]
 [0 5 7]]


In [23]:
print(np.row_stack([M1, M2]))
print(np.column_stack([M1, M2]))
print(np.hstack([M1, M2]))
print(np.vstack([M1, M2]))

[[4 5 6]
 [1 2 3]
 [2 8 9]
 [0 5 7]]
[[4 5 6 2 8 9]
 [1 2 3 0 5 7]]
[[4 5 6 2 8 9]
 [1 2 3 0 5 7]]
[[4 5 6]
 [1 2 3]
 [2 8 9]
 [0 5 7]]


In [24]:
# Original Image
img1 = cv2.resize(img, None, fx=0.5, fy=0.5)
# Affine Image
img2 = cv2.resize(img_affine, None, fx=0.5, fy=0.5)
# Final Image
final_image = np.hstack([img1, img2])

In [22]:
cv2.imshow('Final Image', final_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [29]:
M1 @ M2.transpose()

array([[102,  67],
       [ 45,  31]])